name: {{appName}}
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  api_com:
    git:
      url: https://github.com/CreevekCZ/api_com
      ref: devel
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.3
  # {{#useHive}}
  hive_flutter: ^1.1.0
  # {{/useHive}}
  hooks_riverpod: ^2.4.9
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  palestine_console: ^0.0.10
  path_provider: ^2.1.1
  sentry_flutter: ^7.13.2
  uuid: ^3.0.7


dev_dependencies:
  analyzer: ^5.12.0
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  # {{#useHive}}
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  # {{/useHive}}
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
