name: {{appName}}
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  api_com:
    git:
      url: https://github.com/CreevekCZ/api_com
      ref: devel
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  go_router: ^9.1.0
  # {{#useHive}}
  hive_flutter: ^1.1.0
  # {{/useHive}}
  hooks_riverpod: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.0
  package_info_plus: ^4.0.1
  palestine_console: ^0.0.10
  path_provider: ^2.0.15
  sentry_flutter: ^7.6.2
  unfocus_widget: ^0.0.4
  uuid: ^3.0.7


dev_dependencies:
  analyzer: ^5.12.0
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  # {{#useHive}}
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  # {{/useHive}}
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
