name: {{appName}}
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  api_com:
    git:
      url: https://github.com/CreevekCZ/api_com
      ref: devel
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.2.0
  go_router: ^5.1.5
  # {{#useHive}}
  hive_flutter: ^1.1.0
  # {{/useHive}}
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  package_info_plus: ^3.0.2
  palestine_console: ^0.0.10
  path_provider: ^2.0.11
  sentry_flutter: ^6.0.1
  unfocus_widget: ^0.0.4
  uuid: ^3.0.5


dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.1.4
  custom_lint: ^0.2.12
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  # {{#useHive}}
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  # {{/useHive}}
  json_serializable: ^6.3.1
  riverpod_generator: ^2.0.0
  riverpod_lint: ^1.1.2




flutter:
  uses-material-design: true
  # assets:
  #   - assets/
